### ISSUE TITLE
Enable ability to run yamllint tool

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-yaml#126]
A very popular linter for yaml file is yamllint but this tool is not calling it which means that it would miss to highlight lots of tests done by it.

**Comment by JPinkney** [comment]
This extension is just the client side for https://github.com/redhat-developer/yaml-language-server. I don't think it makes sense to include that tool directly because it doubles up the parse time of the yaml. We would have to run one parse to create the AST thats useable for normal diagnostics/diagnostics with json and then another parse for the yamllint tool for every single change in the yaml. I think it would make more sense to create enhacements to https://github.com/mulesoft-labs/yaml-ast-parser or someone can create a vscode extension that uses yamllint.

**Comment by ssbarnea** [comment]
I think the issue is still valid and linting yaml must happen before AST is built.

When it comes to performance, it can be enabled/disable via configuration.

**Comment by gorkem** [comment]
> I think the issue is still valid and linting yaml must happen before AST is built.

I do not get this statement does that mean yamllinter happens without a parser?
