### ISSUE TITLE
Outlink - Too large for showing

### ISSUE THREAD

**Issue by chatelao** [redhat-developer/vscode-yaml#163]
A rather little .yaml file (13k Lines) reports "too large for showing" in the outline tab.

**Comment by chatelao** [comment]
[PSD2 Yaml](https://berlingroup.stackstorage.com/s/35Bq6pldIaUR4Vs)

**Comment by JPinkney** [comment]
Hi! Apparently VSCode was limiting the amount of symbols that could be displayed in their outline view to 7500 previously and that file was _juuuustttt_ over the limit [1]. However, you're in luck because they removed that limit for the next release. If you try out the insiders build everything works as expected.

[1] - https://stackoverflow.com/questions/54871255/visual-studio-code-file-too-large-for-outline
