### ISSUE TITLE
Syntax checker for ansible blockinfile module shows error on valid syntax.

### ISSUE THREAD

**Issue by DanielvanderZee** [redhat-developer/vscode-yaml#199]
Steps to reproduce:
Create a YAML file with:
  ```
- name: somename
  blockinfile:
    path: "/path/to/some/file"
    block: |
      sometext
      moretext
```

Expected result:
Valid Ansible file

Observed result:
1 Problem: `Missing property "dest".`

As of Ansible 2.3, the blockinfile module has been changed. The parameters `dest`, `destfile` and `name` have been replaced with `path`. The syntax checker does not recognize this new syntax.

**Comment by JPinkney** [comment]
It looks like the problem has to do with one of the ansible schemas. By default the extension pulls in the [ansible 2.5 schema](https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L15) but it looks like the schema must not be correct (though I'm not experienced enough in ansible to know). However, because those schemas don't live in this repository (we pull them from the json schema store) you'll have to file a report here: https://github.com/SchemaStore/schemastore

**Comment by ssbarnea** [comment]
Anything related to Ansible schemas should go to https://github.com/ansible/schemas
