### ISSUE TITLE
String-typed anchor marked with error 'Incorrect type. Expected "object".' if filename is .gitlab-ci.yml

### ISSUE THREAD

**Issue by AndiDog** [redhat-developer/vscode-yaml#201]
Example:

```
.some_key: &the_anchor |
  raw
  multiline
  string

use:
  - the
  - anchor
  - here
  - *the_anchor
```

It seems the extension lints the content against certain schemas. If the filename is `.gitlab-ci.yml`, and only then, the following errors show up (i.e. at two places):

```
Matches multiple schemas when only one must validate. [1, 24]
Incorrect type. Expected "object". [1, 24]
Matches multiple schemas when only one must validate. [7, 3]
Incorrect type. Expected "object". [7, 3]
```

This is valid YAML, and also accepted by GitLab runners, since dotted keys like `.some_key` are ignored and can therefore be used for anchors.

**Comment by JPinkney** [comment]
I'm not too sure on gitlab specific syntax because that's being pulled in from https://github.com/SchemaStore/schemastore but if it's being accepted by gitlab ci then I'm assuming everything should be working.

Since this looks to be an issue with an external schema -- rather than vscode-yaml itself, can you file this issue https://github.com/SchemaStore/schemastore instead

**Comment by AndiDog** [comment]
Makes sense, since vscode-yaml shows no issue with a different filename.
