### ISSUE TITLE
Enable formatter for "Ansible"-Language

### ISSUE THREAD

**Issue by max06** [redhat-developer/vscode-yaml#209]
Good evening.

I installed the vscode-ansible extension to make use of their syntax highlighting and snippets. For that I changed the file-association in this project to "Ansible". Now I want to use your yaml formatter to automatically clean up the files I'm working on.

Sadly, vscode complains about a missing formatter for the "ansible"-language, and I haven't found any possibility to bind your formatter for that language.

Did I miss anything? Can you add the "ansible"-language as a supported type?

Thanks in advance.

**Comment by JPinkney** [comment]
I don't think we would be able to add it in here since that extension looks like it spawns up their own language server. 

If we registered our features for ansible file-associations I believe hover, syntax validation, document symbols etc would all throw duplicates because there would two language servers running.

Since they decided to spawn up their own language server, rather than depending on this extension, they will probably have to add it on their side.

**Comment by max06** [comment]
Thank you very much for looking into this 👍 

I'll open an issue with them, maybe they can solve this on their side ☺️
