### ISSUE TITLE
vscode suggestion should respect the enum order

### ISSUE THREAD

**Issue by virusdefender** [redhat-developer/vscode-yaml#211]
I'm using the schema from https://chaitin.github.io/xray/assets/yaml-poc-schema.json

![image](https://user-images.githubusercontent.com/4939404/62519791-df0b3100-b85e-11e9-996f-9851c99dc574.png)

It seems the suggestion items are ordered by dict order?

![image](https://user-images.githubusercontent.com/4939404/62519721-bedb7200-b85e-11e9-9409-49952247bf1b.png)

I think it should respect the order in schema, because the frequently used items should occur first.

**Comment by fbricon** [comment]
I believe this is VS Code itself listing enums alphabetically, I don't think we can do anything about it on our side

**Comment by JPinkney** [comment]
I looked into this on the most recent version using:
```
{
     "properties": {
         "test": {
             "enum": [
                 "D",
                 "C",
                 "B",
                 "A"
             ]
         }
     }
}
```

and unfortunately, there isn't anything we can do from our side. The yaml language server responds with the enums in the correct order but it looks like VSCode re-orders those responses alphabetically like @fbricon said. Since there isn't anything we can from our side I'm going to close this issue.
