### ISSUE TITLE
Matches multiple schemas when only one must validate.

### ISSUE THREAD

**Issue by pytimer** [redhat-developer/vscode-yaml#247]
## vscode setting

```json
{
    "yaml.format.enable": true,
    "yaml.completion": true,
    "yaml.trace.server": "verbose",
    "yaml.schemas": {
        "file:///D:/vscode-yaml-schemas/kubernetes-json-schema/v1.14.0-standalone-strict/all.json": "*.yml"
    }
}
```

I download `kubernetes-json-schema` to my Windows pc, and setting it like above.
I create a new `test.yml` , but when i input `ap`, it show error that `Matches multiple schemas when only one must validate.`,  i don't know what is wrong.
I see the issue https://github.com/redhat-developer/vscode-yaml/issues/208, but i don't know where can i see the schema version?

**Comment by JPinkney** [comment]
The problem is inside of that schema its constructed something like:

```
{
    "oneOf": [
        {
            "properties": {
                "apiVersion": {
                    "type": "string",
                    "enum": [
                        "v1"
                    ]
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "Deployment"
                    ]
                }
            }
        },
        {
            "properties": {
                "apiVersion": {
                    "type": "string",
                    "enum": [
                        "v1"
                    ]
                },
                "kind": {
                    "type": "string",
                    "enum": [
                        "Pod"
                    ]
                }
            }
        }
    ]
}
```

which means that when you type `ap` its matching both the first part item in oneOf and the second. If you use the built in kubernetes schema available by setting
```
"yaml.schemas": {
    "kubernetes": "test.yml"
}
``` 
then you won't get that issue because that error is explicitily removed when using `kubernetes` as the schema. However if you want to use the other schema you still can, the `matchings multiple schemas when only one must validate` just means you need to provide more yaml before the parser knows which part of the json schema you're trying to use.

I.e. if you do:
```
apiVersion: v1
kind: Deployment
```
you won't have that error anymore

**Comment by pytimer** [comment]
@JPinkney Thanks for you reply. My pc can not access `kubernetes` schema url, so i want to download it to my pc manually. Could i move the kubernetes json schema to specified path, vscode-yaml `kubernetes` schema can use it, is it ok?

**Comment by JPinkney** [comment]
Only the schema that's hardcoded will be the one that automatically disables the error. If you download a schema and use that you can just disregard the error. It's more of a warning anyways
