### ISSUE TITLE
Multiple 'custom' schemes doesn't work

### ISSUE THREAD

**Issue by evidolob** [redhat-developer/vscode-yaml#273]
When my (Tekton) extension contributes JSON scheme for tekton pipeline yaml file, along side with k8's extension, I got error in editor `Matches multiple schemas when only one must validate.` And it seems that only one scheme is taken in to account for code completion and validation. 
Screenshot:
<img width="919" alt="Screenshot 2020-01-28 at 14 59 46" src="https://user-images.githubusercontent.com/929743/73266517-b2b5e900-41df-11ea-9729-fce78a8cacbf.png">

Gitst with json scheme:
https://gist.github.com/evidolob/2cb80710b8dc239677715e10c90e2d7b

**Comment by JPinkney** [comment]
When you are doing completion/hover etc is it matching the tekton schema or the k8s schema? Because K8s and tekton yaml files look to be so similiar its probably matching one of the k8s schemas as well as the tekton schema

**Comment by evidolob** [comment]
I think, it matches k8s, especially when file has errors

**Comment by evidolob** [comment]
K8s is provide scheme for tekton pipeline file with uri: `kubernetes://schema/tekton.dev/v1alpha1@pipeline`

**Comment by JPinkney** [comment]
I'm not sure the best way to go about this. Perhaps disable matches multiple schema error reporting when two schemas are coming from register contributor for one file? Because it's technically not an error if it's matching both schemas at the same time because it thinks they're "equal". (When there is error in yaml files its very very hard to tell which schema to use)

@gorkem WDYT? Should we just disable the error in this case?

**Comment by gorkem** [comment]
Should this actually be an `anyOf` instead of `oneOf`
