### ISSUE TITLE
Wrong indent on Array auto completion

### ISSUE THREAD

**Issue by mliotinoca** [redhat-developer/vscode-yaml#286]
I have this JSON schema which contains an array property:
```JSON
...,
"Entity": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name. It must begin by capital letter followed by any characters.",
          "pattern": "^[A-Z][\\w]*$"
        },
        "description": {
          "type": "string",
          "description": "Description.",
          "minLength": 3
        },
      "fields": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Field"
          },
          "description": "Fields."
        }
      },
      "required": ["description", "name"],
      "additionalProperties": false
    },
    "Field": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name. It must begin by any letter followed by any characters.",
          "pattern": "^[a-zA-Z]+[\\w]*$"
        },
        "type": {
          "anyOf": [{
            "$ref": "#/definitions/PrimitiveTypes"
          }, {
            "type": "string"
          }],
          "description": "Data type."
        },
        "description": {
          "type": "string",
          "description": "Description.",
          "minLength": 2
        },
        "isPublic": {
          "type": "boolean",
          "description": "Set access of field."
        },
        "isNullable": {
          "type": "boolean",
          "description": "Set field as nullable."
        },
      },
      "required": ["name", "type", "description"],
      "additionalProperties": false
    },
...
```
The desired layout on auto completition is like this:
```YAML
fields:
  - name:
    description:
```
but, the "description" property has an extra indentation:
```YAML
fields:
  - name:
      description:
```

**Comment by JPinkney** [comment]
I've just tried with: https://gist.githubusercontent.com/JPinkney/98d208c930fe79e638e481a3021fe560/raw/0b02a0cbbb840d3dfaf2cd0256cc3e73ebd45c57/test_schema.json and tried autocompleting like this:
```
Entity:
  name: 
  description: 
  | <- here
```
and it seems like everything is indenting correctly in the newest version

**Comment by TedDriggs** [comment]
@JPinkney I'm still seeing a problem with this, but it might be due to using 4-space tabs instead of 2-space tabs.

<img width="266" alt="Array Completion Indentation" src="https://user-images.githubusercontent.com/4805575/108213385-d1856700-70e3-11eb-8449-ad22cec18087.png">

To get to this point, I dedented out of the previous array item, pressed `-`, then accepted the completion for the array item. I'm using prettier with `tabWidth: 4` in my `.prettierrc` file; that wasn't enough to get VSCode to understand the intended behavior of Shift-Tab so I also have `.vscode/settings.json` setting `"[yaml]": { "editor.tabSize": 4 }`. I think the problem is that something is counting the number of indentation levels but isn't aware of the special handling for array items.

Should I file a new issue for this, or would you like to reuse this one?

**Comment by JPinkney** [comment]
Open a new issue please

**Comment by TedDriggs** [comment]
Filed #432
