### ISSUE TITLE
Inconsistent validation based on file extension (file.yml vs file.yaml)

### ISSUE THREAD

**Issue by OpsTalkJordan** [redhat-developer/vscode-yaml#288]
Upon saving a yaml file as .yml previous valid yaml syntax reports invalid. 

Operating System: Windows 10
VS Code Release: 1.43.1
YAML Extension Version: 0.7.2

Steps to reproduce: 

1. Open a new workspace. 
2. Set language mode to YAML. 
3. Insert valid yaml syntax, for example: 
```
plugins:
  - name: "Plugin 1"
    date: "Mar 21 2020"
    licenseKey: |
      line1
      line2

  - name: "Plugin 2"
    date: "Mar 21 2020"
    licenseKey: |
      line1
      line2
```
4. Save file without specifying extension (defaults to .yml)

> File > Save > "fileName" 

At this point all previously valid syntax reports 'Incorrect type. Expected "string".' 

5. Save file specifying the yaml extension.  

> File > Save as > "fileName.yaml"

All syntax now reports correct again. 

Specifically the filename I tested with is "myAppConfig" and follows the exact same formatting as above. It is being saved in the default Windows 10 document folder and using "Spaces 2" indentation. Verified no trailing white space and that both files validate fine with a up to data Python3 yamllint install.

**Comment by JPinkney** [comment]
Most likely the file name you are using is automatically associating with one of the schemas from http://schemastore.org/json/ based on:

> Incorrect type. Expected "string".'

because the only way this should show is if its comparing against a json schema.

If you want to turn off this feature you can turn off `yaml.schemaStore.enable`

**Comment by gorkem** [comment]
Closing since this went silent

**Comment by vdh** [comment]
@JPinkney @gorkem So is there any way to actually debug or fix this issue with the Schema Store? It's impossible to even figure out *what* it's pulling from the store, because the error messages don't explain or provide sources for themselves.

This seems like it's a pretty big flaw in the Schema Store feature if it just silently picks a false positive for validation. It took me quite a while to trace it back to *this* extension and *this* particular issue, simply because `Missing property "app".` was an *extremely* unhelpful error message that failed to mention neither the validator (`vscode-yaml`), nor what incorrect schema it decided to randomly pick for my `.mocharc.yml` file.

**Comment by JPinkney** [comment]
The only way is to fix it is to modify the json schema in the json schema store repository https://github.com/SchemaStore/schemastore

**Comment by vdh** [comment]
@JPinkney _Which_ schema file…? This is the issue.

**Comment by gorkem** [comment]
Extending diagnostics is a pood idea opened https://github.com/redhat-developer/yaml-language-server/issues/310
