### ISSUE TITLE
Feature to Hide Potential Secrets in Editor

### ISSUE THREAD

**Issue by eashi** [redhat-developer/vscode-yaml#295]
Hi,

I have had the idea to create a VSCode extension that would hide secretsin YAML files in editor, that would be especially good for presenters and streamers. 

I wanted to parse elements in YAML and find keys like "cert", or "connectionstring" or of the like, I found that the best way to achieve it was through your parser rather parsing it by myself.

So I was thinking maybe this can be a feature in this `vscode-yaml` extension, or maybe I can borrow code from this repo to be able to do that. I would highly prefer the first :D.

What do you think folks? If you would like this to be a feature in this extension and that it aligns with your vision and direction, then maybe I can take a stab in implementing it?

**Comment by JPinkney** [comment]
I think it would be a pretty cool feature but it seems like something that should be a separate extension (maybe something like YAML Presenter?) rather than a feature that exists in this repo.

With that said, I think what you should be able to do is grab the text of the document -> run it through https://github.com/mulesoft-labs/yaml-ast-parser (this is the parser we use) -> traverse the ast and find nodes that you want to hide and then obfuscate cert/connectionstring etc.

I'm going to close this issue since we won't take the feature here but if you end up creating it feel free to ping me!
