### ISSUE TITLE
Consider collaborating/merging with `adamvoss/vscode-yaml`

### ISSUE THREAD

**Issue by schickling** [redhat-developer/vscode-yaml#35]
There seems to be a related project: https://github.com/adamvoss/vscode-yaml

Are there any plans to collaborate or even merge the projects together? Neither project seems to be ready for "prime-time" so it would be great if efforts could be joined 👍

**Comment by JPinkney** [comment]
Hi, at the current moment we have integrated Adam's https://github.com/adamvoss/vscode-yaml-languageservice in our project and have been in talks with Adam! AFAIK he isn't going to be doing much maintenance on the vscode-yaml-languageservice once this extension is released. Ours functions very similar to his already (due to some reliance on his awesome language service!) but has a few extra features (such as autocompletion) but I will work on getting it ready for prime time.
