### ISSUE TITLE
Appveyor autocomplete is missing a lot of fields

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-yaml#45]
With this schema:
```
  "yaml.schemas": {
    "http://json.schemastore.org/appveyor":"appveyor.yml"
  }
```
Autocompletion only returns a handful of choices:
<img width="530" alt="screen shot 2017-11-22 at 4 38 20 pm" src="https://user-images.githubusercontent.com/148698/33150921-b719d156-cfa3-11e7-8aaf-0b8b60762192.png">

compared to what http://json.schemastore.org/appveyor defines. It seems only the content of the `allOf` node is returned.

**Comment by JPinkney** [comment]
The language server only uses properties/anyOf/allOf to generate autocompletion results. However, I think there is a bug in this language server and the json language server because image/init/clone_folder etc should be shown via "$ref": "#/definitions/job" as well. For some reason its returning the only the first result in the allOf.

**Comment by JPinkney** [comment]
I've just tried this and inspected the schema and it looks good to go now. I don't know much about appveyor itself but all the things that should be coming up in autocompletion are now.
