### ISSUE TITLE
VScode validates devfile.yaml v2 with devfile.json v1 schema validator when using both OpenShift Connector Extension and redhat.vscode-yaml extension 

### ISSUE THREAD

**Issue by ggianini** [redhat-developer/vscode-yaml#503]
## Describe the bug

I'm using a fedora machine

As far as I can see, for some reason, the redhat.vscode-yaml extension uses [Json Schema Store](https://www.schemastore.org/json/) to call [Eclipse Che Devfile](https://raw.githubusercontent.com/eclipse/che/7.19.2/wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json) that is a devfile v1 Schema to validate a [devfile.yaml v2](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-quarkus/devfile.yaml).

So when working with VScode OpenShift Connector Extension to provide an application that uses [devfile.yaml v2](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-quarkus/devfile.yaml), VScode keeps telling me that this devfile.yaml has lots of syntax errors, even though OpenShift Connector [has devfile v2 support](https://github.com/redhat-developer/vscode-openshift-tools/blob/master/schemas/devfile.schema.json). The OpenShift connector file on my local machine even has this same devfile.json schema at (~/.vscode/extensions/redhat.vscode-openshift-connector-0.2.5/schemas/devfile.schema.json) but it's not used to validate the [devfile.yaml](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-quarkus/devfile.yaml) (the [remote file](https://raw.githubusercontent.com/eclipse/che/7.19.2/wsmaster/che-core-api-workspace/src/main/resources/schema/1.0.0/devfile.json) is used instead), even though the code works properly and the aplication runs normally

Syntax Problems on devfile.yaml

![Problems Tab](https://user-images.githubusercontent.com/50370164/117552641-0f2ec780-b023-11eb-91ce-66c13281618f.png)

Package Structure

![Package Structure](https://user-images.githubusercontent.com/50370164/117552664-2e2d5980-b023-11eb-9951-ec450087a757.png)

API-Imported v1 schema validator shows path when I hover my mouse over the file

![API-Imported v1 schema validator](https://user-images.githubusercontent.com/50370164/117553176-58344b00-b026-11eb-9ca3-a6b89071a176.png)

Running app:

![Running APP](https://user-images.githubusercontent.com/50370164/117552798-012d7680-b024-11eb-81f8-c482217399b0.png)

The app I'm using is a Quarkus quickstart provided by OpenShift Connector via [devfile](https://github.com/odo-devfiles/registry/blob/master/devfiles/java-quarkus/devfile.yaml) but the behaviour is the same with the springboot option. (VScode uses a remote devfile.json v1 schema file to validade the v2 devfile.yaml)

The code works properly on OpenShift local server

## Expected Behavior
VScode should use a devfile.json v2 schema to validade v2 devfile.yaml
## Current Behavior
VScode uses a remote devfile.json v1 schema file to validade the v2 devfile.yaml

## Steps to Reproduce

1. Install both OpenShift Connector extension and redhat.vscode-yaml extension on VScode
2. Use OpenShift Connector native quarkus component to provision app via devfile
3. Verify that there are reports of syntax problems on devfile.yaml 

## Environment
- [ ] Windows
- [ ] Mac
- [X] Linux
- [ ] other (please specify)

**Comment by JPinkney** [comment]
To me it looks like vscode-yaml is behaving correctly. Even though the openshift connector plugin has the schema in the repository, it does not seem to be associating the devfile v2 schema to devfile.yaml anywhere. Since the openshift-connector is not associating the schema anywhere, it uses the default schema from the json schema store (which is the devfile v1).

In order for the openshift connector plugin to have devfile v2 working they need to use one of our several contribution points such as https://github.com/redhat-developer/vscode-yaml#mapping-a-schema-in-an-extension or https://github.com/redhat-developer/vscode-yaml/wiki/Extension-API#register-contributor.

Once they use one of those extension points then when a user installs the openshift connector plugin and opens devfile.yaml it will automatically be validated against the devfile v2 schema.
