### ISSUE TITLE
Ignore yarn.lock files

### ISSUE THREAD

**Issue by Deilan** [redhat-developer/vscode-yaml#56]
Add a support for [yarn lockfile v1](https://yarnpkg.com/lang/en/docs/yarn-lock/).

Currently an opened `yarn.lock` file looks like this:

![image](https://user-images.githubusercontent.com/4777512/35048932-908ed35a-fbaf-11e7-98eb-20763c3f2ea4.png)

**Comment by JPinkney** [comment]
It looks like yarn is semi-yaml but not quite fully but I could be wrong because those look like errors thrown by https://github.com/mulesoft-labs/yaml-ast-parser

**Comment by iDVB** [comment]
Is there a way to tell vscode to ignore `yarn.lock` files in terms of syntax testing? Or to tell it to test as though it were a plain txt file?

**Comment by JPinkney** [comment]
A little late on the response but I'll look to see if we can ignore that file. It shouldn't be picked up at all since its not actual yaml. I could be wrong but it seems as though VSCode is associating it with yaml for some reason.

**Comment by grillbiff** [comment]
if you want `yarn.lock` ignored until this is fixed you can change the Language Mode of the file to i.e. `plain text` and it won't get picked up by the validator.

**Comment by JPinkney** [comment]
[VSCode has now removed yarn.lock from the yaml language contribution](https://github.com/Microsoft/vscode/commit/13471d3b4bd39d9fe0e2bc948506acb4fe33cf03) so yarn.lock will no longer be associated with yaml. I'm closing this now because its fixed on both sides. All that is required is to upgrade to new VSCode version that doesn't have that language contribution and the vscode-yaml release that will happen monday.
