### ISSUE TITLE
very slow completion with aws cloudformation schema

### ISSUE THREAD

**Issue by v-au** [redhat-developer/vscode-yaml#626]
## Describe the bug
When Yaml Completion is enabled it takes 20+ seconds for the Intellisense list to pop up.

## Expected Behavior
Intellisense should popup instantly.

## Current Behavior
20+ seconds until the completion list shows up.

## Steps to Reproduce
Enable/disable YAML Completion. See attached screen capture.

## Environment
- [x ] Windows
- [ ] Mac
- [ ] Linux
- [ ] other (please specify)

https://user-images.githubusercontent.com/86463740/139240163-31c62f43-8b8c-4b8b-8578-d966b8474aa6.mp4

**Comment by remcohaszing** [comment]
A practical example can be found [here](https://gitlab.com/appsemble/amersfoort/-/blob/main/apps/werkplek-reservering/app-definition.yaml). There’s no need to install yarn dependencies or even to clone the repo. Just downloading the file as `app-definition.yaml` should be sufficient to reproduce the issue.

The problem is much worse in another much larger `app-definition.yaml` file I’m currently working with, but unfortunately it’s proprietary. This makes me think the issue may be related not (only) to schema complexity, but also to complexity of the YAML contents.

Using VSCode YAML 0.23.0 completion is pretty much instantaneous.

Using VSCode YAML 1.0.0 or 1.1.0 completion is slow, as described in this issue.

Using VSCode YAML 1.1.1 shows an error that the JSON schema reference can’t be resolved. This is a new issue.

**Comment by evidolob** [comment]
@remcohaszing thx, now I can profile work with https://gitlab.com/appsemble/amersfoort/-/blob/main/apps/werkplek-reservering/app-definition.yaml to find the problem

**Comment by evidolob** [comment]
I found the problem and seems to fix it:

https://user-images.githubusercontent.com/929743/140893906-9b081929-61e7-4fc3-8d1d-3d90cc3cac51.mov

Completion list shows in 10-20 times faster 🥳 
Preparing PR today.
