### ISSUE TITLE
Automatically insert colon on autocomplete

### ISSUE THREAD

**Issue by bary12** [redhat-developer/vscode-yaml#78]
When autocompleting an object property, I don't see a reason why one would not want to add the colon right after. Currently only the name is inserted, without a colon.

**Comment by gorkem** [comment]
Perhaps it should be a setting?

**Comment by JPinkney** [comment]
I've been experimenting with this on a local branch and it seems much faster to develop yaml files using this. Theres still a few bugs but its almost there. It should be up in the next few days then we can evaluate.

**Comment by JPinkney** [comment]
Added in 0.0.12 release.

**Comment by Dessix** [comment]
> @gorkem: Perhaps it should be a setting?

At this point, it has become an issue in the derived extension [ansible/vscode-ansible](/ansible/vscode-ansible) in their issue ansible/vscode-ansible#953; they've stated in that thread that this is something that would need addressed at this extension's level.

Is there any way to avoid these colons in autocompletion candidates, since they keep inserting into mustache filters in strings?
